# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL61uLkDDnqXqtwpEHziPpvrB8PXuNrl
"""

name="Anuska"
age=23
age2=age+1

print("my name is:",name)
print("my age last year:" ,age)
print("my current age is:",age2)

name="Anuska"
age=20
price=37.89
print(type(name))
print(type(age))
print(type(price))

name1="sk"
name2='sk'
name3='''sk'''

print(name1)
print(name2)
print(name3)

age=23
old=False
a= None
print(type(old))
print(type(a))

a=5
b=2
sum=a+b
print(sum)

a=5
b=2
sub=a-b
print(sub)

#a=c , single comment
print(23)
# multi-line comment

#Aritheatic operators
a=50
b=20

print("sum :", a+b)
print("Diff :",a-b)
print("Mul :", a*b)
print("Div :", a/b)
print("Modular:", a%b)#remainder
print("Power :", a**b)#a^b=a**b

#relational operators
a = 50
b = 20

print("a==b:", a==b)
print("a!=b:", a!=b)
print("a>=b:", a>=b)
print("a>b:", a>b)
print("a<=b:", a<=b)
print("a<b:", a<b)

a=10
b=9
print(a>=b)